# ===================================================================
# CONFIGURAÇÃO PRINCIPAL (PARA PRODUÇÃO E GITHUB)
# ===================================================================

# Ativa o perfil 'dev' por padrão se nenhum outro for especificado
spring.profiles.active=dev

# --- Configuração do Banco de Dados ---
# Usa variáveis de ambiente (para o servidor) ou valores padrão (para dev)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gestao_ingressos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuração do JPA / Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Configuração do Token JWT ---
api.security.token.secret=${JWT_SECRET:12345678}

# --- Configuração de Email (para o servidor) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
